import { createClient } from '@supabase/supabase-js'
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const startupData = [
  // ─── FOODTECH ────────────────────────────────────────
  { name: 'TinyOwl', industry_vertical: 'foodtech', business_model: 'Marketplace', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'failed', outcome_year: 2016, outcome_details: 'Burned $17M. Delivery cost Rs100 exceeded margin Rs30. Unit economics never worked at any scale.', founded_year: 2014, shutdown_year: 2016, data_source: 'manual', data_verified: true },
  { name: 'Zomato', industry_vertical: 'foodtech', business_model: 'Marketplace', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'ipo', outcome_year: 2021, outcome_details: 'IPO at $8.6B. Achieved profitability 2023. Duopoly with Swiggy. Acquired Blinkit.', founded_year: 2008, data_source: 'manual', data_verified: true },
  { name: 'Swiggy', industry_vertical: 'foodtech', business_model: 'Marketplace', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'ipo', outcome_year: 2024, outcome_details: 'IPO 2024. $15B valuation. Expanded into quick commerce with Instamart.', founded_year: 2014, data_source: 'manual', data_verified: true },
  { name: 'FreshMenu', industry_vertical: 'foodtech', business_model: 'Subscription', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'failed', outcome_year: 2020, outcome_details: 'Cloud kitchen model with Rs300 average meals. Could not scale profitably. Shut down during COVID.', founded_year: 2014, shutdown_year: 2020, data_source: 'manual', data_verified: true },
  { name: 'EatFit', industry_vertical: 'foodtech', business_model: 'Subscription', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'active', outcome_details: 'Acquired by CURE.fit. Healthy food subscription with 50K orders/day.', founded_year: 2017, data_source: 'manual', data_verified: true },

  // ─── EDTECH ──────────────────────────────────────────
  { name: "Byju's", industry_vertical: 'edtech', business_model: 'Subscription', market_tier: 'India Tier 1', target_segment: 'Students', outcome: 'failed', outcome_year: 2024, outcome_details: 'Collapsed from $22B valuation. Aggressive sales tactics, debt acquisitions of WhiteHat Jr and Aakash, course completion below 30%.', founded_year: 2011, shutdown_year: 2024, data_source: 'IBBI', data_verified: true },
  { name: 'Vedantu', industry_vertical: 'edtech', business_model: 'Subscription', market_tier: 'India Tier 1', target_segment: 'Students', outcome: 'active', outcome_details: 'Survived post-pandemic crash. 200K+ paid subscribers. Cut costs 80% to reach profitability.', founded_year: 2014, data_source: 'manual', data_verified: true },
  { name: 'Unacademy', industry_vertical: 'edtech', business_model: 'Subscription', market_tier: 'India Tier 2', target_segment: 'Students', outcome: 'active', outcome_details: '$3.4B valuation. 50M+ learners. Dominant in UPSC and JEE prep.', founded_year: 2015, data_source: 'manual', data_verified: true },
  { name: 'Physics Wallah', industry_vertical: 'edtech', business_model: 'Subscription', market_tier: 'India Tier 2', target_segment: 'Students', outcome: 'active', outcome_details: 'Unicorn 2022. Disrupted Byju with Rs999/year pricing vs Rs50000. 10M+ paid students.', founded_year: 2020, data_source: 'manual', data_verified: true },
  { name: 'Classplus', industry_vertical: 'edtech', business_model: 'Subscription', market_tier: 'India Tier 2', target_segment: 'Small Businesses', outcome: 'active', outcome_details: '$600M valuation. 150K+ coaching institutes. B2B EdTech for local coaching market.', founded_year: 2018, data_source: 'manual', data_verified: true },
  { name: 'Toppr', industry_vertical: 'edtech', business_model: 'Subscription', market_tier: 'India Tier 1', target_segment: 'Students', outcome: 'acquired', outcome_year: 2021, outcome_details: 'Acquired by Byju for $150M. Never profitable on its own. High CAC problem.', founded_year: 2013, data_source: 'manual', data_verified: true },
  { name: 'Embibe', industry_vertical: 'edtech', business_model: 'Subscription', market_tier: 'India Tier 2', target_segment: 'Students', outcome: 'active', outcome_details: 'Acquired by Reliance. AI-powered learning personalization platform.', founded_year: 2012, data_source: 'manual', data_verified: true },
  { name: 'Doubtnut', industry_vertical: 'edtech', business_model: 'Ads', market_tier: 'India Tier 2', target_segment: 'Students', outcome: 'acquired', outcome_year: 2023, outcome_details: 'Acquired by Allen Career Institute. Vernacular doubt-solving app with 30M users.', founded_year: 2017, data_source: 'manual', data_verified: true },

  // ─── FINTECH ─────────────────────────────────────────
  { name: 'Razorpay', industry_vertical: 'fintech', business_model: 'Pay per use', market_tier: 'India Tier 1', target_segment: 'Small Businesses', outcome: 'active', outcome_details: '$7.5B valuation. Dominant B2B payment gateway. Developer-friendly API drove adoption.', founded_year: 2014, data_source: 'manual', data_verified: true },
  { name: 'CRED', industry_vertical: 'fintech', business_model: 'Marketplace', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'active', outcome_details: '$6.4B valuation. Premium credit card users only. Unique positioning in high-value segment.', founded_year: 2018, data_source: 'manual', data_verified: true },
  { name: 'PhonePe', industry_vertical: 'fintech', business_model: 'Pay per use', market_tier: 'India Tier 2', target_segment: 'Working Professionals', outcome: 'active', outcome_details: '$12B valuation. 450M+ users. Largest UPI app by transaction volume.', founded_year: 2015, data_source: 'manual', data_verified: true },
  { name: 'Paytm', industry_vertical: 'fintech', business_model: 'Marketplace', market_tier: 'India Tier 2', target_segment: 'Working Professionals', outcome: 'active', outcome_details: 'IPO 2021 at $20B valuation. Struggled post-IPO. RBI action on Paytm Payments Bank 2024.', founded_year: 2010, data_source: 'manual', data_verified: true },
  { name: 'Groww', industry_vertical: 'fintech', business_model: 'Pay per use', market_tier: 'India Tier 2', target_segment: 'Working Professionals', outcome: 'active', outcome_details: '$3B valuation. 10M+ active investors. Democratized mutual funds for first-time investors.', founded_year: 2016, data_source: 'manual', data_verified: true },
  { name: 'BharatPe', industry_vertical: 'fintech', business_model: 'Pay per use', market_tier: 'India Tier 2', target_segment: 'Small Businesses', outcome: 'active', outcome_details: '$2.85B valuation. QR code payments for kirana stores. Founder removed due to governance issues.', founded_year: 2018, data_source: 'manual', data_verified: true },
  { name: 'Khatabook', industry_vertical: 'fintech', business_model: 'Subscription', market_tier: 'India Tier 2', target_segment: 'Small Businesses', outcome: 'active', outcome_details: '$600M valuation. 10M+ SMBs. Digital ledger replacing paper khata for shopkeepers.', founded_year: 2019, data_source: 'manual', data_verified: true },
  { name: 'ZestMoney', industry_vertical: 'fintech', business_model: 'Pay per use', market_tier: 'India Tier 2', target_segment: 'Working Professionals', outcome: 'failed', outcome_year: 2023, outcome_details: 'Shut down after Goldman Sachs acquisition fell through. High NPA rates in BNPL segment.', founded_year: 2015, shutdown_year: 2023, data_source: 'manual', data_verified: true },
  { name: 'LazyPay', industry_vertical: 'fintech', business_model: 'Pay per use', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'active', outcome_details: 'Acquired by PayU. BNPL product with 3M+ users.', founded_year: 2017, data_source: 'manual', data_verified: true },
  { name: 'RupeeRedee', industry_vertical: 'fintech', business_model: 'Pay per use', market_tier: 'India Tier 2', target_segment: 'Working Professionals', outcome: 'failed', outcome_year: 2025, outcome_details: 'RBI digital lending norms and mounting NPAs forced shutdown.', founded_year: 2018, shutdown_year: 2025, data_source: 'manual', data_verified: true },

  // ─── GROCERY / QUICK COMMERCE ────────────────────────
  { name: 'Zepto', industry_vertical: 'grocery delivery', business_model: 'Marketplace', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'active', outcome_details: '$1.4B valuation. 10-minute grocery delivery via dark stores. Unit economics work at scale.', founded_year: 2021, data_source: 'manual', data_verified: true },
  { name: 'Peppertap', industry_vertical: 'grocery delivery', business_model: 'Marketplace', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'failed', outcome_year: 2016, outcome_details: 'Raised $51M. CAC 10x LTV. Grocery margins 3-5% cannot support delivery costs.', founded_year: 2014, shutdown_year: 2016, data_source: 'manual', data_verified: true },
  { name: 'BigBasket', industry_vertical: 'grocery delivery', business_model: 'Marketplace', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'acquired', outcome_year: 2021, outcome_details: 'Acquired by Tata Group for $1.3B. Largest online grocery in India.', founded_year: 2011, data_source: 'manual', data_verified: true },
  { name: 'Grofers', industry_vertical: 'grocery delivery', business_model: 'Marketplace', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'pivoted', outcome_year: 2021, outcome_details: 'Rebranded to Blinkit. Pivoted to quick commerce. Acquired by Zomato for $568M.', founded_year: 2013, data_source: 'manual', data_verified: true },
  { name: 'Dunzo', industry_vertical: 'logistics', business_model: 'Pay per use', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'failed', outcome_year: 2025, outcome_details: 'App offline Jan 2025. Rs400Cr debt. Failed to compete with Blinkit and Zepto unit economics.', founded_year: 2015, shutdown_year: 2025, data_source: 'manual', data_verified: true },

  // ─── ECOMMERCE ───────────────────────────────────────
  { name: 'Meesho', industry_vertical: 'ecommerce', business_model: 'Marketplace', market_tier: 'India Tier 2', target_segment: 'Working Professionals', outcome: 'active', outcome_details: '$4.9B valuation. 150M+ customers. Social commerce for Tier 2/3 via WhatsApp resellers.', founded_year: 2015, data_source: 'manual', data_verified: true },
  { name: 'Nykaa', industry_vertical: 'ecommerce', business_model: 'Marketplace', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'ipo', outcome_year: 2021, outcome_details: 'IPO at $13B. First profitable Indian unicorn IPO. Beauty category trust building.', founded_year: 2012, data_source: 'manual', data_verified: true },
  { name: 'Lenskart', industry_vertical: 'ecommerce', business_model: 'Marketplace', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'active', outcome_details: '$4.5B valuation. Profitable. Blended online+offline worked uniquely for eyewear.', founded_year: 2010, data_source: 'manual', data_verified: true },
  { name: 'Snapdeal', industry_vertical: 'ecommerce', business_model: 'Marketplace', market_tier: 'India Tier 2', target_segment: 'Working Professionals', outcome: 'active', outcome_details: 'Survived Flipkart/Amazon war by pivoting to value commerce for Tier 2/3 buyers.', founded_year: 2010, data_source: 'manual', data_verified: true },
  { name: 'Shopclues', industry_vertical: 'ecommerce', business_model: 'Marketplace', market_tier: 'India Tier 2', target_segment: 'Working Professionals', outcome: 'acquired', outcome_year: 2019, outcome_details: 'Acquired by Qoo10 for undisclosed amount. Lost to Meesho and Amazon in value segment.', founded_year: 2011, data_source: 'manual', data_verified: true },

  // ─── SOCIAL MEDIA ────────────────────────────────────
  { name: 'ShareChat', industry_vertical: 'social media', business_model: 'Ads', market_tier: 'India Tier 2', target_segment: 'Students', outcome: 'active', outcome_details: '$5B valuation. 160M+ users in 15 Indian languages. Dominant vernacular social platform.', founded_year: 2015, data_source: 'manual', data_verified: true },
  { name: 'Hike Messenger', industry_vertical: 'social media', business_model: 'Ads', market_tier: 'India Tier 1', target_segment: 'Students', outcome: 'failed', outcome_year: 2021, outcome_details: 'Shut down messaging after $261M raised. Could not overcome WhatsApp network effects.', founded_year: 2012, shutdown_year: 2021, data_source: 'manual', data_verified: true },
  { name: 'Koo', industry_vertical: 'social media', business_model: 'Ads', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'failed', outcome_year: 2024, outcome_details: 'Shut down May 2024. Twitter alternative could not sustain without network effects.', founded_year: 2020, shutdown_year: 2024, data_source: 'manual', data_verified: true },
  { name: 'Moj', industry_vertical: 'social media', business_model: 'Ads', market_tier: 'India Tier 2', target_segment: 'Students', outcome: 'active', outcome_details: 'ShareChat-owned short video app. 160M+ users post TikTok ban.', founded_year: 2020, data_source: 'manual', data_verified: true },

  // ─── HEALTHTECH ──────────────────────────────────────
  { name: 'Practo', industry_vertical: 'healthtech', business_model: 'Marketplace', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'active', outcome_details: '$550M valuation. Doctor discovery and teleconsultation. COVID boosted adoption significantly.', founded_year: 2008, data_source: 'manual', data_verified: true },
  { name: 'PharmEasy', industry_vertical: 'healthtech', business_model: 'Marketplace', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'active', outcome_details: 'Largest online pharmacy. IPO delayed due to valuation concerns. Profitable on core business.', founded_year: 2015, data_source: 'manual', data_verified: true },
  { name: '1mg', industry_vertical: 'healthtech', business_model: 'Marketplace', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'acquired', outcome_year: 2021, outcome_details: 'Acquired by Tata Group. Integrated into Tata Health super-app.', founded_year: 2012, data_source: 'manual', data_verified: true },
  { name: 'Cure.fit', industry_vertical: 'healthtech', business_model: 'Subscription', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'active', outcome_details: '$1.5B valuation. Fitness centers + digital health. COVID caused major pivot to digital.', founded_year: 2016, data_source: 'manual', data_verified: true },

  // ─── LOGISTICS ───────────────────────────────────────
  { name: 'Delhivery', industry_vertical: 'logistics', business_model: 'Pay per use', market_tier: 'India Tier 2', target_segment: 'Small Businesses', outcome: 'ipo', outcome_year: 2022, outcome_details: 'IPO at $5.4B. Profitable at scale. Built India-wide last-mile network.', founded_year: 2011, data_source: 'manual', data_verified: true },
  { name: 'Porter', industry_vertical: 'logistics', business_model: 'Marketplace', market_tier: 'India Tier 1', target_segment: 'Small Businesses', outcome: 'active', outcome_details: 'Unicorn 2025. Intra-city freight for SMBs. Dominated mini-truck logistics.', founded_year: 2014, data_source: 'manual', data_verified: true },
  { name: 'Rivigo', industry_vertical: 'logistics', business_model: 'Pay per use', market_tier: 'India Tier 2', target_segment: 'Small Businesses', outcome: 'acquired', outcome_year: 2022, outcome_details: 'Acquired by DTDC. Truck relay model reduced transit time 40% but could not raise sufficient capital.', founded_year: 2014, data_source: 'manual', data_verified: true },
  { name: 'Shadowfax', industry_vertical: 'logistics', business_model: 'Pay per use', market_tier: 'India Tier 2', target_segment: 'Small Businesses', outcome: 'active', outcome_details: '$220M raised. Last-mile delivery for ecommerce and quick commerce. Profitable unit economics.', founded_year: 2015, data_source: 'manual', data_verified: true },

  // ─── TRAVELTECH ──────────────────────────────────────
  { name: 'OYO Rooms', industry_vertical: 'traveltech', business_model: 'Marketplace', market_tier: 'India Tier 2', target_segment: 'Working Professionals', outcome: 'active', outcome_details: '$9B valuation at peak. Profitable in India core. International expansion struggles.', founded_year: 2013, data_source: 'manual', data_verified: true },
  { name: 'Stayzilla', industry_vertical: 'traveltech', business_model: 'Marketplace', market_tier: 'India Tier 2', target_segment: 'Working Professionals', outcome: 'failed', outcome_year: 2017, outcome_details: 'Voluntarily shut after 13 years. Two-sided marketplace never scaled. OYO took the market.', founded_year: 2005, shutdown_year: 2017, data_source: 'manual', data_verified: true },
  { name: 'ixigo', industry_vertical: 'traveltech', business_model: 'Marketplace', market_tier: 'India Tier 2', target_segment: 'Working Professionals', outcome: 'ipo', outcome_year: 2024, outcome_details: 'IPO 2024. Travel aggregator for budget travelers. Profitable on train and bus bookings.', founded_year: 2007, data_source: 'manual', data_verified: true },

  // ─── B2B / SAAS ──────────────────────────────────────
  { name: 'Moglix', industry_vertical: 'b2b ecommerce', business_model: 'Marketplace', market_tier: 'India Tier 1', target_segment: 'Small Businesses', outcome: 'active', outcome_details: '$2.6B valuation. B2B industrial supplies. Sticky enterprise customers.', founded_year: 2015, data_source: 'manual', data_verified: true },
  { name: 'Darwinbox', industry_vertical: 'SaaS', business_model: 'Subscription', market_tier: 'India Tier 1', target_segment: 'Enterprises', outcome: 'active', outcome_details: '$1B valuation. HR tech for enterprises. Beat SAP and Workday in mid-market India.', founded_year: 2015, data_source: 'manual', data_verified: true },
  { name: 'Zoho', industry_vertical: 'SaaS', business_model: 'Subscription', market_tier: 'India Tier 1', target_segment: 'Small Businesses', outcome: 'active', outcome_details: '$15B+ valuation. Bootstrapped. 100M+ users. Profitable every year. Global SaaS leader.', founded_year: 1996, data_source: 'manual', data_verified: true },
  { name: 'Freshworks', industry_vertical: 'SaaS', business_model: 'Subscription', market_tier: 'Global', target_segment: 'Small Businesses', outcome: 'ipo', outcome_year: 2021, outcome_details: 'IPO on NASDAQ at $12B. Customer support SaaS. Second Indian SaaS unicorn after Zoho.', founded_year: 2010, data_source: 'manual', data_verified: true },
  { name: 'Builder.ai', industry_vertical: 'SaaS', business_model: 'Pay per use', market_tier: 'Global', target_segment: 'Small Businesses', outcome: 'failed', outcome_year: 2025, outcome_details: 'Collapsed at $1.5B valuation. Low net retention. Sales-driven growth masked poor product.', founded_year: 2016, shutdown_year: 2025, data_source: 'manual', data_verified: true },

  // ─── AGRITECH ────────────────────────────────────────
  { name: 'DeHaat', industry_vertical: 'agritech', business_model: 'Marketplace', market_tier: 'India Tier 2', target_segment: 'Small Businesses', outcome: 'active', outcome_details: '$700M valuation. End-to-end farm services for 1M+ farmers. Input supply + output aggregation.', founded_year: 2012, data_source: 'manual', data_verified: true },
  { name: 'Ninjacart', industry_vertical: 'agritech', business_model: 'Marketplace', market_tier: 'India Tier 2', target_segment: 'Small Businesses', outcome: 'active', outcome_details: 'Acquired stake by Walmart/Flipkart. Farm-to-retail supply chain. Rs2000Cr+ GMV.', founded_year: 2015, data_source: 'manual', data_verified: true },
  { name: 'Otipy', industry_vertical: 'agritech', business_model: 'Marketplace', market_tier: 'India Tier 2', target_segment: 'Working Professionals', outcome: 'failed', outcome_year: 2025, outcome_details: 'Shut down May 2025. Quick commerce platforms stole the urban grocery-buyer.', founded_year: 2019, shutdown_year: 2025, data_source: 'manual', data_verified: true },

  // ─── MOBILITY ────────────────────────────────────────
  { name: 'Ola Electric', industry_vertical: 'mobility', business_model: 'Marketplace', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'ipo', outcome_year: 2024, outcome_details: 'IPO 2024. Largest EV two-wheeler maker in India. Manufacturing-first strategy.', founded_year: 2017, data_source: 'manual', data_verified: true },
  { name: 'BluSmart', industry_vertical: 'mobility', business_model: 'Fleet-owned', market_tier: 'India Tier 1', target_segment: 'Working Professionals', outcome: 'failed', outcome_year: 2025, outcome_details: 'Shut down April 2025. SEBI exposed Rs262Cr fraud at Gensol Engineering (fleet owner).', founded_year: 2019, shutdown_year: 2025, data_source: 'SEBI', data_verified: true },
  { name: 'Rapido', industry_vertical: 'mobility', business_model: 'Marketplace', market_tier: 'India Tier 2', target_segment: 'Working Professionals', outcome: 'active', outcome_details: '$830M valuation. Bike taxi pioneer. Expanded to auto and cabs. Profitable in bike segment.', founded_year: 2015, data_source: 'manual', data_verified: true },

  // ─── AI / DEEP TECH ──────────────────────────────────
  { name: 'Neysa', industry_vertical: 'AI Infrastructure', business_model: 'Pay per use', market_tier: 'India Tier 1', target_segment: 'Enterprises', outcome: 'active', outcome_details: 'Unicorn Feb 2026. Sovereign AI cloud for India. GPU-as-a-service.', founded_year: 2023, data_source: 'manual', data_verified: true },
  { name: 'Sarvam AI', industry_vertical: 'AI', business_model: 'Pay per use', market_tier: 'India Tier 1', target_segment: 'Enterprises', outcome: 'active', outcome_details: 'Indic-language LLM. Government contracts for AI in Hindi and 22 regional languages.', founded_year: 2023, data_source: 'manual', data_verified: true },
  { name: 'Subtl AI', industry_vertical: 'AI', business_model: 'Subscription', market_tier: 'Global', target_segment: 'Working Professionals', outcome: 'failed', outcome_year: 2025, outcome_details: 'Thin LLM wrapper. OpenAI and Google integrated native RAG making product redundant.', founded_year: 2021, shutdown_year: 2025, data_source: 'manual', data_verified: true },

  // ─── HARWARE / D2C ───────────────────────────────────
  { name: 'Juicero', industry_vertical: 'd2c', business_model: 'Subscription', market_tier: 'Global', target_segment: 'Consumer', outcome: 'failed', outcome_year: 2017, outcome_details: 'Raised $120M for a $400 juicer. Product was over-engineered while value was zero compared to hand-squeezing.', founded_year: 2013, shutdown_year: 2017, data_source: 'manual', data_verified: true },
  { name: 'Quibi', industry_vertical: 'streaming', business_model: 'Subscription', market_tier: 'Global', target_segment: 'Consumer', outcome: 'failed', outcome_year: 2020, outcome_details: 'Raised $1.75B. Ignored extreme behavioral friction of forcing paid short-form video against free TikTok.', founded_year: 2018, shutdown_year: 2020, data_source: 'manual', data_verified: true },

  // ─── WEB3 ────────────────────────────────────────────
  { name: 'Celsius', industry_vertical: 'web3', business_model: 'Yield', market_tier: 'Global', target_segment: 'Consumer', outcome: 'failed', outcome_year: 2022, outcome_details: 'Bankrupt. Unsustainable yield generation resembling a Ponzi. Risk underwriting was non-existent.', founded_year: 2017, shutdown_year: 2022, data_source: 'manual', data_verified: true },
  // ─── PROPTECH / REAL ESTATE ────────────────────────────
  { name: 'WeWork', industry_vertical: 'proptech', business_model: 'Arbitrage', market_tier: 'Global', target_segment: 'Enterprises', outcome: 'failed', outcome_year: 2023, outcome_details: 'Bankrupt. Burned $20B+. Masqueraded as a tech company while operating a capital-intensive real estate arbitrage model.', founded_year: 2010, shutdown_year: 2023, data_source: 'manual', data_verified: true },

  // ─── GIG ECONOMY / MARKETPLACE ───────────────────────
  { name: 'Homejoy', industry_vertical: 'marketplace', business_model: 'Marketplace', market_tier: 'Global', target_segment: 'Consumer', outcome: 'failed', outcome_year: 2015, outcome_details: 'Raised $40M. Shut down due to severe platform leakage and high customer acquisition costs.', founded_year: 2012, shutdown_year: 2015, data_source: 'manual', data_verified: true },

  // ─── FINTECH (PAYMENTS) ──────────────────────────────
  { name: 'Fast', industry_vertical: 'fintech', business_model: 'Pay per use', market_tier: 'Global', target_segment: 'Small Businesses', outcome: 'failed', outcome_year: 2022, outcome_details: 'Raised $124M. Burned $10M a month while generating less than $600k in annual revenue. Zero moat against Stripe.', founded_year: 2019, shutdown_year: 2022, data_source: 'manual', data_verified: true },

  // ─── HEALTHTECH (HARDWARE) ───────────────────────────
  { name: 'Theranos', industry_vertical: 'healthtech', business_model: 'Hardware+Pay per use', market_tier: 'Global', target_segment: 'Consumer', outcome: 'failed', outcome_year: 2018, outcome_details: 'Raised $1.4B. Outright systemic fraud. Bypassed peer review entirely and siloed engineering teams to hide physics failures.', founded_year: 2003, shutdown_year: 2018, data_source: 'manual', data_verified: true },
]

const postmortemData = [
  { startup_name: 'TinyOwl', primary_failure_reason: 'Unit economics never worked at any scale', failure_category: 'financial', detailed_analysis: 'Average order value was Rs200 but delivery cost was Rs80-100. With payment gateway fees and restaurant commission, each order lost money. They tried to grow volume to solve the problem but volume only made losses bigger. The fundamental model was broken from day one.', missed_signals: ['CAC Rs800 per customer but LTV Rs400', 'Delivery cost never came below 40% of order value', 'Swiggy was better funded and operationally superior'], lessons_learned: ['Unit economics must work at small scale before expanding', 'Food delivery requires massive scale to be profitable', 'Geographic concentration beats city-wide spread for hyperlocal'], months_before_obvious: 8, source_type: 'manual_analysis' },
  { startup_name: 'Peppertap', primary_failure_reason: 'Grocery margins cannot support delivery economics', failure_category: 'financial', detailed_analysis: 'Grocery margins in India are 3-5%. At scale, they needed to charge delivery fees that customers refused to pay. Free delivery burned cash. Paid delivery drove users away. The model required scale that Indian grocery economics could not support for a standalone player.', missed_signals: ['Grocery margins in India are 3-5% vs 20-30% needed', 'Indian consumers refused delivery charges above Rs20', 'BigBasket had 5-year head start on supply chain'], lessons_learned: ['Margin structure determines delivery business viability', 'Grocery delivery requires proprietary supply chain', 'In price-sensitive markets delivery fee kills adoption'], months_before_obvious: 12, source_type: 'manual_analysis' },
  { startup_name: 'Hike Messenger', primary_failure_reason: 'Cannot displace messaging app with network effects already established', failure_category: 'competition', detailed_analysis: 'Hike raised $261M and had 100M+ users but could never displace WhatsApp. The core problem was network effects — users are on WhatsApp because their contacts are on WhatsApp. No feature advantage could overcome this. Hike tried stickers, games, and payments but none were reasons to switch.', missed_signals: ['WhatsApp had 200M India users when Hike launched', 'No messaging app has ever displaced an incumbent anywhere globally', 'Users refused to convince contacts to switch platforms'], lessons_learned: ['Network effect businesses are winner-take-all', 'Feature differentiation cannot overcome switching costs when network is the product', 'Find a niche WhatsApp does not serve rather than competing head-on'], months_before_obvious: 24, source_type: 'manual_analysis' },
  { startup_name: "Byju's", primary_failure_reason: 'Aggressive sales tactics masked poor product retention', failure_category: 'product', detailed_analysis: 'BYJU used high-pressure sales to sell Rs50000-80000 courses. Course completion below 30%. Revenue recognition manipulated. When COVID edtech boom ended, underlying business was exposed. Debt-funded acquisitions of Aakash, WhiteHat Jr added costs without synergy.', missed_signals: ['Course completion rates below 30%', 'Sales force 6x larger than engineering team', 'Parent complaints about aggressive sales ignored', 'Post-COVID edtech usage dropped 60% globally'], lessons_learned: ['Sales growth cannot hide retention problems', 'EdTech success is learning outcomes not enrollment', 'Debt-funded acquisitions in unprofitable businesses are fatal'], months_before_obvious: 18, source_type: 'manual_analysis' },
  { startup_name: 'Dunzo', primary_failure_reason: 'Delivery cost structure never viable at any scale', failure_category: 'financial', detailed_analysis: 'Each Dunzo delivery cost Rs60-80 but average margin was Rs15-24. Even at scale each delivery lost Rs40-60. Reliance investment was not enough. Zepto succeeded by focusing on grocery with large basket sizes.', missed_signals: ['Delivery cost Rs75 vs Rs20 sustainable threshold', 'Category mix too diverse — different economics per category', 'Zepto proved model works only with large grocery baskets'], lessons_learned: ['Quick commerce works only with high average order value', 'Category focus beats diversity in hyperlocal', 'Delivery cost is fixed — only basket size improvement helps'], months_before_obvious: 12, source_type: 'manual_analysis' },
  { startup_name: 'Koo', primary_failure_reason: 'Twitter alternative cannot survive without network effects', failure_category: 'competition', detailed_analysis: 'Koo was a Twitter clone for Indian languages. Despite government support and initial hype during Twitter controversies, users kept returning to Twitter/X because their networks were there. Content creators refused to split attention across platforms.', missed_signals: ['Twitter network effects stronger than political controversy', 'No social platform has successfully cloned Twitter anywhere', 'Creator monetization on Koo was zero vs Twitter ad revenue'], lessons_learned: ['Social media is winner-take-all per content type', 'Political controversy does not translate to sustained platform switching', 'Vernacular alone is not sufficient differentiation'], months_before_obvious: 6, source_type: 'manual_analysis' },
  { startup_name: 'ZestMoney', primary_failure_reason: 'BNPL NPA rates unsustainable in Indian market', failure_category: 'financial', detailed_analysis: 'ZestMoney offered BNPL to thin-file customers. Default rates reached 8-12% vs 2-3% sustainable threshold. RBI tightened digital lending norms. Goldman Sachs acquisition fell through due to NPA concerns. The target customer segment — new-to-credit consumers — had much higher default rates than projected.', missed_signals: ['NPA rates 4x higher than projections in first 12 months', 'RBI signaling tighter BNPL regulation from 2022', 'Target segment new-to-credit users are highest default risk'], lessons_learned: ['Credit underwriting must be proven before scaling', 'Regulatory risk in fintech must be modeled as a core assumption', 'BNPL works in markets with strong credit bureau data — India lacks this'], months_before_obvious: 14, source_type: 'manual_analysis' },
  { startup_name: 'Stayzilla', primary_failure_reason: 'Two-sided marketplace in hospitality requires solving supply quality problem', failure_category: 'product', detailed_analysis: 'Stayzilla operated for 13 years but never cracked supply quality. Budget accommodations in India had massive quality variance. Customers could not trust what they would get. OYO solved this by standardizing the rooms themselves rather than just listing them. Stayzilla remained a listing platform.', missed_signals: ['Review variance too high — same property scored 2 and 5 stars', 'OYO growing 300% YoY by 2016 while Stayzilla was flat', 'Budget traveler primary concern is quality certainty not price discovery'], lessons_learned: ['Marketplace in quality-variable categories requires quality guarantee not just listing', 'OYO insight: own the experience not just the marketplace', 'Two-sided marketplace must solve the trust problem on both sides'], months_before_obvious: 18, source_type: 'manual_analysis' },
  { startup_name: 'BluSmart', primary_failure_reason: 'Founder fraud at holding company destroyed the operational business', failure_category: 'governance', detailed_analysis: 'BluSmart had a working EV ride-hailing model with strong NPS and unit economics improving. However, SEBI discovered Rs262Cr was siphoned from Gensol Engineering (the fleet owner controlled by same founders) through fraudulent loan diversion. The operating business was sound but founder fraud made it unrescuable.', missed_signals: ['Gensol share price manipulation detected by market watchers 6 months before SEBI action', 'Fleet ownership and ride-hailing under same founders was conflict of interest', 'Debt at Gensol was 5x EBITDA — unsustainable'], lessons_learned: ['Founder governance must be evaluated as rigorously as business model', 'Related party transactions between founder entities are highest fraud risk', 'EV infrastructure and service operations should be separate entities'], months_before_obvious: 3, source_type: 'SEBI Investigation 2025' },
  { startup_name: 'Subtl AI', primary_failure_reason: 'Thin wrapper on LLM API has no moat when platform integrates natively', failure_category: 'product', detailed_analysis: 'Subtl AI built a productivity layer on top of OpenAI APIs. When OpenAI released GPT-4o with native voice, vision, and task completion in 2024, and Google released Gemini with workspace integration, the entire value proposition of thin wrapper startups evaporated overnight. There was no proprietary data, no switching cost, no distribution moat.', missed_signals: ['OpenAI roadmap clearly showed native integrations coming', 'No proprietary training data or fine-tuning', 'Customer acquisition cost increasing as OpenAI marketed direct'], lessons_learned: ['AI products need proprietary data moat not just prompt engineering', 'Build on top of AI infrastructure only if you own the distribution or data', 'Thin wrappers have 12-18 month window before platform closes the gap'], months_before_obvious: 4, source_type: 'manual_analysis' },
  { startup_name: 'Quibi', primary_failure_reason: 'Total misalignment with ingrained consumer behavioral friction', failure_category: 'product', detailed_analysis: 'Quibi spent $1.75B assuming Hollywood production values in 10-minute chunks would convince users to pay a subscription. They completely ignored that TikTok and YouTube had already captured this time-slot for free. The behavioral friction of making someone pay for something they already solve for free is insurmountable, regardless of capital.', missed_signals: ['Users already had free alternatives (TikTok)', 'Paid short-form video had no historical precedent', 'Launched during pandemic when commuting (their target use case) disappeared'], lessons_learned: ['Capital cannot buy behavioral shifts if free alternatives exist', 'Content production value does not override platform network effects', 'Never fight ingrained dopamine loops without a 10x better free wedge'], months_before_obvious: 1, source_type: 'manual_analysis' },
  { startup_name: 'Celsius', primary_failure_reason: 'Unsustainable yield Ponzi dynamics masked as innovation', failure_category: 'financial', detailed_analysis: 'Celsius offered 18% yields on crypto deposits, functioning like a bank but without reserve requirements. To pay those yields, they engaged in extremely high-risk opaque lending. When macro conditions tightened, the structural insolvency became a classic bank run.', missed_signals: ['Yields outpaced all organic market growth', 'Zero transparency on lending counter-parties', 'Founders aggressively cashing out personal tokens'], lessons_learned: ['If you do not know where the yield comes from, you are the yield', 'Regulatory arbitrage is not a defensible business model', 'Illiquid high-risk lending with liquid liabilities always ends in runs'], months_before_obvious: 12, source_type: 'manual_analysis' },
  { startup_name: 'WeWork', primary_failure_reason: 'Asset-liability duration mismatch masked by absurd "tech" valuations', failure_category: 'financial', detailed_analysis: 'WeWork took on 15-year long-term commercial lease liabilities while selling month-to-month short-term sub-leases. This asset-liability mismatch meant that in any downturn, revenue would evaporate immediately while massive fixed costs remained. They tried to claim "tech" multiples (20x revenue) for a low-margin traditional real estate arbitrage business.', missed_signals: ['Claiming software margins on physical real estate', 'Extreme founder governance total-control issues', 'No actual lock-in or switching costs for members'], lessons_learned: ['You cannot slap a tech valuation on a physical arbitrage model', 'Mismatching duration of liabilities and assets is structurally fatal', 'Growth capital cannot mask fundamentally low gross margins'], months_before_obvious: 24, source_type: 'manual_analysis' },
  { startup_name: 'Homejoy', primary_failure_reason: 'Structural platform leakage that destroyed LTV vs CAC', failure_category: 'product', detailed_analysis: 'Homejoy connected homeowners with house cleaners. However, cleaning is a high-trust, recurring service. Once Homejoy introduced a good cleaner to a homeowner, the two parties would simply exchange phone numbers and transact entirely off-platform to avoid the 20% platform fee. Homejoy paid the high CAC but lost all the LTV to platform leakage.', missed_signals: ['Retention dropped off a cliff after the first 2 bookings', 'Focusing on acquiring new customers instead of locking in the supply side', 'Failure to provide software tools to cleaners that would keep them on-platform'], lessons_learned: ['If the recurring value is the human connection, the platform will be disintermediated', 'Marketplaces must provide ongoing SaaS value to prevent platform leakage', 'CAC/LTV math assumes you capture the lifetime value — leakage breaks this instantly'], months_before_obvious: 18, source_type: 'manual_analysis' },
  { startup_name: 'Fast', primary_failure_reason: 'Absurd burn rate with zero defensible product moat', failure_category: 'financial', detailed_analysis: 'Fast raised $124M to build "1-click checkout". The founder scaled headcount to 400+ people, burning up to $10M a month. However, the core product was essentially a thin feature that Stripe and Shopify could (and did) implement natively in a weekend. They achieved less than $600k in annual revenue before running out of cash.', missed_signals: ['Hiring 400 people before finding product-market fit', 'Confusing massive PR hype and VC funding with actual market traction', 'Competing directly with Stripe and Apple without proprietary data'], lessons_learned: ['Do not scale headcount until unit economics are proven positive', 'A feature is not a platform if incumbents already own the distribution', 'High burn rate without corresponding revenue acceleration is corporate suicide'], months_before_obvious: 10, source_type: 'manual_analysis' },
  { startup_name: 'Theranos', primary_failure_reason: 'Bypassing the fundamental laws of physics and peer review', failure_category: 'governance', detailed_analysis: 'Theranos claimed to run hundreds of tests on a single drop of blood. This defied fundamental physics regarding fluid dynamics and sample sizes. To hide this, the CEO strictly siloed internal teams so no one saw the full picture, actively dodged independent peer review, and intimidated whistleblowers. It was the ultimate fake-it-till-you-make-it culture applied dangerously to healthcare.', missed_signals: ['Refusal to publish findings in peer-reviewed medical journals', 'Board of directors consisted of politicians and military generals, not medical scientists', 'Extreme secrecy internally with compartmentalized science teams'], lessons_learned: ['Fake-it-till-you-make-it works for software bugs, not for the laws of physics or biology', 'If the board lacks domain expertise, they cannot exercise fiduciary oversight', 'Secrecy is a red flag for fraud when evaluating deep-tech feasibility'], months_before_obvious: 36, source_type: 'manual_analysis' },
]

const indiaInsights = [
  { sector: 'all', tier: 'tier2', insight_type: 'consumer_behavior', insight_text: 'Tier 2 and Tier 3 Indian consumers will not pay for anything available for free. WhatsApp, YouTube, and Google Maps set zero-price expectation. Any B2C startup targeting Tier 2 must offer free tier and monetize through SMBs or indirectly.', evidence: 'ShareChat ARPU $0.10/month vs Instagram India $0.80/month', affects_score_factor: 'revenueScore', score_adjustment: -8, still_relevant: true, insight_year: 2024, data_source: 'manual' },
  { sector: 'all', tier: 'all', insight_type: 'competition_landscape', insight_text: 'Any Indian startup competing with WhatsApp in messaging, Google in search, or Jio in telecom will fail. These have network effects so strong no feature advantage can displace them. Find niches they do not serve — do not compete in their core markets.', evidence: 'Hike raised $261M and failed. Koo shut down after $50M. Every Indian messaging alternative failed.', affects_score_factor: 'competition', score_adjustment: -25, still_relevant: true, insight_year: 2024, data_source: 'manual' },
  { sector: 'edtech', tier: 'tier2', insight_type: 'consumer_behavior', insight_text: 'Indian students in Tier 2/3 prefer recorded content over live classes. They watch at 1.5-2x speed and share accounts among 3-5 friends. Subscription works only below Rs500/month. Above that physical coaching is preferred.', evidence: 'Unacademy Rs1000-3000/month struggles with Tier 2. Physics Wallah Rs999/year has 10M paid students.', affects_score_factor: 'feasibility', score_adjustment: -5, still_relevant: true, insight_year: 2024, data_source: 'manual' },
  { sector: 'fintech', tier: 'tier2', insight_type: 'trust_patterns', insight_text: 'Tier 2 consumers have low trust in new fintech for large transactions. They use PhonePe or GPay (trusted brands) but are reluctant to invest or take loans from unknown apps. New fintech needs 12-18 months trust-building before real money transactions.', evidence: 'PhonePe and GPay have 85% UPI market share. New entrants get less than 1% despite better features.', affects_score_factor: 'marketDemand', score_adjustment: -6, still_relevant: true, insight_year: 2024, data_source: 'manual' },
  { sector: 'grocery delivery', tier: 'tier1', insight_type: 'pricing_sensitivity', insight_text: 'Indian grocery consumers refuse delivery fees above Rs25-30 for orders below Rs500. Quick commerce works because basket sizes are Rs400-600 and time savings justify the cost. Low basket size grocery delivery is not viable.', evidence: 'Peppertap failed when delivery fees raised above Rs20. Zepto requires Rs499 minimum for free delivery.', affects_score_factor: 'feasibility', score_adjustment: -10, still_relevant: true, insight_year: 2024, data_source: 'manual' },
  { sector: 'social media', tier: 'tier2', insight_type: 'language_preference', insight_text: 'Tier 2/3 users strongly prefer regional language content. Hindi, Tamil, Telugu, Marathi, Bengali get 5-8x more engagement than English. Any social or content platform targeting Tier 2 must invest in vernacular from day one.', evidence: 'ShareChat 160M users in 15 languages. Moj and Josh dominate short video in Tier 2.', affects_score_factor: 'marketDemand', score_adjustment: 8, still_relevant: true, insight_year: 2024, data_source: 'manual' },
  { sector: 'marketplace', tier: 'all', insight_type: 'consumer_behavior', insight_text: 'Two-sided marketplace in India faces a cold start problem. Suppliers do not join without buyers, buyers do not come without suppliers. Indian suppliers are more price-sensitive on commission. Commission above 15% drives suppliers to find direct channels.', evidence: 'Stayzilla failed after 13 years. Urban Company and Meesho solved supply side first before demand.', affects_score_factor: 'feasibility', score_adjustment: -12, still_relevant: true, insight_year: 2024, data_source: 'manual' },
  { sector: 'all', tier: 'tier1', insight_type: 'competition_landscape', insight_text: 'India Tier 1 cities are the most competitive startup markets. Every consumer category has 3-5 funded startups. CAC is 3-4x higher in Tier 1 than Tier 2. First-time founders should launch in Tier 2 first for product-market fit.', evidence: 'CAC in Bangalore for consumer apps Rs800-1200 vs Rs200-400 in Tier 2.', affects_score_factor: 'competition', score_adjustment: -8, still_relevant: true, insight_year: 2024, data_source: 'manual' },
  { sector: 'b2b', tier: 'all', insight_type: 'consumer_behavior', insight_text: 'Indian SMBs pay for software only if it directly saves or makes money within 30 days. They do not pay for productivity, collaboration, or analytics tools. Khatabook, Vyapar, OkCredit succeeded because they replaced physical ledgers — direct cost saving.', evidence: 'Khatabook 10M+ paying SMBs. Productivity SaaS for Indian SMBs consistently failed.', affects_score_factor: 'revenueScore', score_adjustment: 5, still_relevant: true, insight_year: 2024, data_source: 'manual' },
  { sector: 'all', tier: 'tier2', insight_type: 'device_usage', insight_text: 'Average Tier 2/3 Indian smartphone has 2-3GB RAM, 32-64GB storage. Apps above 50MB or slow on 4G get uninstalled. WhatsApp-first behavior means features must work within or alongside WhatsApp to succeed.', evidence: 'App uninstall rate in Tier 2 is 60% within 7 days if app is above 50MB or slow.', affects_score_factor: 'feasibility', score_adjustment: -4, still_relevant: true, insight_year: 2024, data_source: 'manual' },
  { sector: 'AI', tier: 'all', insight_type: 'platform_risk', insight_text: 'AI wrapper startups with no proprietary data or distribution have an 18-month window before the underlying platform integrates natively. Building on OpenAI or Google APIs without owning data, fine-tuning, or distribution is existential risk.', evidence: 'Subtl AI failed 2025. Multiple AI wrapper startups shut down after GPT-4o and Gemini releases.', affects_score_factor: 'innovation', score_adjustment: -20, still_relevant: true, insight_year: 2025, data_source: 'manual' },
  { sector: 'fintech', tier: 'all', insight_type: 'regulatory', insight_text: 'RBI digital lending norms 2022-2024 killed BNPL and predatory lending startups. Any fintech involving credit to thin-file or new-to-credit customers faces high NPA risk and regulatory scrutiny. Compliance is not optional — it is a core product constraint.', evidence: 'ZestMoney shut 2023. RupeeRedee shut 2025. Multiple BNPL startups restructured or failed.', affects_score_factor: 'feasibility', score_adjustment: -15, still_relevant: true, insight_year: 2025, data_source: 'manual' },
  { sector: 'agritech', tier: 'tier2', insight_type: 'market_opportunity', insight_text: 'Rural smartphone penetration reached 82% in 2025 enabling direct-to-farm models. Farmers are now reachable digitally but trust is earned only through physical presence first. Hybrid agritech models (digital + field agents) outperform pure digital by 3x in adoption.', evidence: 'DeHaat uses field agents + app model. Pure digital agritech companies have 5-8% adoption in target villages.', affects_score_factor: 'marketDemand', score_adjustment: 10, still_relevant: true, insight_year: 2025, data_source: 'manual' },
  { sector: 'all', tier: 'all', insight_type: 'mortality', insight_text: 'Over 11,223 Indian startups shut down in 2025 — 30% increase YoY. B2C ecommerce accounted for 50% of shutdowns. Main causes: unit economics failure (40%), regulatory changes (25%), competition from funded players (20%), governance issues (15%).', evidence: 'DPIIT Data 2025. Jasaro LLP startup mortality report.', affects_score_factor: 'risk', score_adjustment: -15, still_relevant: true, insight_year: 2026, data_source: 'DPIIT' },
  { sector: 'd2c', tier: 'tier1', insight_type: 'capital_efficiency', insight_text: 'CAC has skyrocketed by 400% on Meta/Google over 3 years. Any D2C brand without >60% gross margins and 40% repeat purchase rate within 6 months will go bankrupt. Paid acquisition as a sole growth engine is dead.', evidence: 'Average D2C CAC now Rs1200, average AOV Rs1500. Only margins >60% survive.', affects_score_factor: 'feasibility', score_adjustment: -20, still_relevant: true, insight_year: 2025, data_source: 'manual' },
  { sector: 'web3', tier: 'all', insight_type: 'regulatory', insight_text: 'India functionally banned crypto trading via 30% flat tax and 1% TDS without loss offsets, destroying 95% of retail volumes. Global tokenomics without real fiat revenue streams are classified as high mortality risk.', evidence: 'WazirX volumes down 90% post-2022 tax laws.', affects_score_factor: 'marketDemand', score_adjustment: -30, still_relevant: true, insight_year: 2025, data_source: 'manual' },
]

const marketSizeData = [
  { industry_vertical: 'edtech', geography: 'India', tam_usd: 7500000000, sam_usd: 2000000000, cagr_percent: 19.5, growth_stage: 'growing', data_year: 2024, projection_year: 2029, avg_cac_usd: 15, avg_ltv_usd: 120, avg_arpu_usd: 8, key_players: ["Byju's", 'Unacademy', 'Vedantu', 'Physics Wallah', 'Classplus'], market_notes: 'Post-pandemic correction 2022-23. Market stabilized. K-12 and test prep strongest segments. Physics Wallah disrupted pricing floor.', data_source: 'manual' },
  { industry_vertical: 'fintech', geography: 'India', tam_usd: 150000000000, sam_usd: 25000000000, cagr_percent: 31, growth_stage: 'growing', data_year: 2024, projection_year: 2029, avg_cac_usd: 8, avg_ltv_usd: 200, avg_arpu_usd: 12, key_players: ['PhonePe', 'Paytm', 'Razorpay', 'CRED', 'Groww'], market_notes: 'UPI transformed payments. Lending and insurance are next. Regulatory environment tightening.', data_source: 'manual' },
  { industry_vertical: 'foodtech', geography: 'India', tam_usd: 8000000000, sam_usd: 3500000000, cagr_percent: 16, growth_stage: 'mature', data_year: 2024, projection_year: 2029, avg_cac_usd: 12, avg_ltv_usd: 80, avg_arpu_usd: 5, key_players: ['Zomato', 'Swiggy'], market_notes: 'Duopoly controls 95% of organized food delivery. Very hard to enter. Quick commerce growing fast.', data_source: 'manual' },
  { industry_vertical: 'grocery delivery', geography: 'India Tier 1', tam_usd: 24000000000, sam_usd: 5000000000, cagr_percent: 22, growth_stage: 'growing', data_year: 2024, projection_year: 2029, avg_cac_usd: 10, avg_ltv_usd: 150, avg_arpu_usd: 18, key_players: ['Zepto', 'Blinkit', 'Swiggy Instamart', 'BigBasket'], market_notes: 'Quick commerce has won Tier 1. Basket size and frequency are key metrics. Dark store economics need scale.', data_source: 'manual' },
  { industry_vertical: 'social media', geography: 'India Tier 2', tam_usd: 5000000000, sam_usd: 800000000, cagr_percent: 25, growth_stage: 'growing', data_year: 2024, projection_year: 2029, avg_cac_usd: 2, avg_ltv_usd: 15, avg_arpu_usd: 0.5, key_players: ['ShareChat', 'Moj', 'Josh', 'Roposo'], market_notes: 'Vernacular content growing 40% YoY. Very low ARPU but massive user base. Ad model only viable monetization.', data_source: 'manual' },
  { industry_vertical: 'healthtech', geography: 'India', tam_usd: 18000000000, sam_usd: 4000000000, cagr_percent: 28, growth_stage: 'growing', data_year: 2024, projection_year: 2029, avg_cac_usd: 20, avg_ltv_usd: 180, avg_arpu_usd: 15, key_players: ['Practo', 'PharmEasy', '1mg', 'Cure.fit'], market_notes: 'COVID accelerated adoption. Teleconsultation normalized. Chronic disease management emerging segment.', data_source: 'manual' },
  { industry_vertical: 'logistics', geography: 'India', tam_usd: 22000000000, sam_usd: 8000000000, cagr_percent: 20, growth_stage: 'growing', data_year: 2024, projection_year: 2029, avg_cac_usd: 5, avg_ltv_usd: 300, avg_arpu_usd: 25, key_players: ['Delhivery', 'Porter', 'Shadowfax', 'Xpressbees'], market_notes: 'Ecommerce growth drives logistics. Quick commerce creating dark store infrastructure. Last-mile profitable at scale.', data_source: 'manual' },
  { industry_vertical: 'AI Infrastructure', geography: 'India', tam_usd: 15000000000, sam_usd: 3000000000, cagr_percent: 45, growth_stage: 'early', data_year: 2025, projection_year: 2030, avg_cac_usd: 50, avg_ltv_usd: 5000, avg_arpu_usd: 200, key_players: ['Neysa', 'Sarvam AI', 'E2E Networks'], market_notes: 'Sovereign AI push from Indian government. GPU shortage creating massive demand. Enterprise AI adoption accelerating.', data_source: 'manual' },
]

async function seedDatabase() {
  console.log('🚀 INITIALIZING FOUNDEROS MASTER KNOWLEDGE BASE v3...')
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')

  // 1. Upsert startups
  const { data: startups, error: sErr } = await supabase
    .from('startups')
    .upsert(startupData, { onConflict: 'name' })
    .select()

  if (sErr) { console.error('❌ Startup Error:', sErr.message); return }
  console.log(`✅ SYNCED ${startups.length} STARTUP RECORDS`)

  // 2. Upsert post-mortems
  let pmCount = 0
  for (const pm of postmortemData) {
    const startup = startups.find(s => s.name === pm.startup_name)
    if (!startup) { console.log(`⚠️  Startup not found: ${pm.startup_name}`); continue }
    const { error } = await supabase
      .from('failure_postmortems')
      .upsert({
        startup_id: startup.id,
        primary_failure_reason: pm.primary_failure_reason,
        failure_category: pm.failure_category,
        detailed_analysis: pm.detailed_analysis,
        missed_signals: pm.missed_signals,
        lessons_learned: pm.lessons_learned,
        months_before_obvious: pm.months_before_obvious,
        source_type: pm.source_type,
      }, { onConflict: 'startup_id' })
    if (error) console.error(`❌ PM error for ${pm.startup_name}:`, error.message)
    else pmCount++
  }
  console.log(`✅ SYNCED ${pmCount} POST-MORTEMS`)

  // 3. Upsert India insights
  const { error: iErr } = await supabase
    .from('india_market_insights')
    .upsert(indiaInsights, { onConflict: 'insight_text' })
  if (iErr) console.error('❌ Insights error:', iErr.message)
  else console.log(`✅ SYNCED ${indiaInsights.length} INDIA MARKET INSIGHTS`)

  // 4. Upsert market size data
  const { error: mErr } = await supabase
    .from('market_size_data')
    .upsert(marketSizeData, { onConflict: 'industry_vertical, geography' })
  if (mErr) console.error('❌ Market data error:', mErr.message)
  else console.log(`✅ SYNCED ${marketSizeData.length} MARKET SIZE RECORDS`)

  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
  console.log('✅ MASTER KNOWLEDGE BASE v3 COMPLETE')
  console.log(`   Startups:      ${startups.length}`)
  console.log(`   Post-mortems:  ${pmCount}`)
  console.log(`   Insights:      ${indiaInsights.length}`)
  console.log(`   Market data:   ${marketSizeData.length}`)
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
}

seedDatabase().catch(console.error)